### ISSUE TITLE
RUNTIME ERROR: Not loading textures 🗡️

### ISSUE THREAD

**Issue by Thiiboy** [to268/PlasmaPurgatory#1]
Commit id : https://github.com/to268/PlasmaPurgatory/commit/3c70e48d6ad4145dc5ca9affbcff401f08029094

**Comment by Thiiboy** [comment]
**Error at Menu.cs:37** 
# Backtrace
```cs
Microsoft.Xna.Framework.Content.ContentLoadException
  HResult=0x80131500
  Message=The content file was not found.
  Source=MonoGame.Framework
  Arborescence des appels de procédure :
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName)
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at PlasmaPurgatory.Menu.LoadContent() in P:\PlasmaPurgatory\PlasmaPurgatory\Menu.cs:line 37
   at PlasmaPurgatory.Game1.LoadContent() in P:\PlasmaPurgatory\PlasmaPurgatory\Game1.cs:line 33
   at PlasmaPurgatory.Game1.Initialize() in P:\PlasmaPurgatory\PlasmaPurgatory\Game1.cs:line 25
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at PlasmaPurgatory.Program.Main() in P:\PlasmaPurgatory\PlasmaPurgatory\Program.cs:line 11

  Cette exception a été levée à l'origine dans cette pile des appels : 
    [Code externe]

Exception interne 1 :
FileNotFoundException : Could not find file 'P:\PlasmaPurgatory\PlasmaPurgatory\bin\Debug\net5.0\PlayButton.xnb'.
```

**Comment by to268** [comment]
The bug has been fixed.
